# -*- coding: utf-8 -*-
"""20_08_2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13thMzSThThy9-r8ZLwbIuNC9XypN-xF6
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/Buketklfa/python_202_Buket_Kalfa.git
# %cd python_202_Buket_Kalfa

# Commented out IPython magic to ensure Python compatibility.
# %cd final-project-second-stage
!pip install -r requirements.txt
!python main.py

# Commented out IPython magic to ensure Python compatibility.
# %cd ../final-project-third-stage
!pip install -r requirements.txt
!pytest test_api.py

!pytest