# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AK_9dI5enKnlNCbFKDy_IY-vehMah_j
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from library import Library

app = FastAPI(title="Kütüphane Yönetim API", version="1.0")
lib = Library()  # JSON verilerini yükle

class ISBNModel(BaseModel):
    isbn: str

@app.get("/books")
def get_books():
    """Kütüphanedeki tüm kitapları listeler"""
    return [book.to_dict() for book in lib.books]

@app.post("/books")
def add_book(isbn_model: ISBNModel):
    """ISBN ile kitap ekler (OpenLibrary API’den veri çekilir)"""
    isbn = isbn_model.isbn
    if any(b.isbn == isbn for b in lib.books):
        raise HTTPException(status_code=400, detail="Bu ISBN zaten mevcut!")
    try:
        lib.add_book_by_isbn(isbn)
        return {"message": "Kitap başarıyla eklendi."}
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))

@app.delete("/books/{isbn}")
def delete_book(isbn: str):
    """ISBN’e göre kitabı siler"""
    if any(b.isbn == isbn for b in lib.books):
        lib.remove_book(isbn)
        return {"message": "Kitap silindi."}
    else:
        raise HTTPException(status_code=404, detail="Kitap bulunamadı.")