# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AK_9dI5enKnlNCbFKDy_IY-vehMah_j
"""

from fastapi.testclient import TestClient
from api import app
import pytest

client = TestClient(app)

def test_get_books():
    response = client.get("/books")
    assert response.status_code == 200
    assert isinstance(response.json(), list)

def test_add_and_delete_book(monkeypatch):
    # API çağrılarını simüle etmek için monkeypatch
    class FakeLibrary:
        def add_book_by_isbn(self, isbn):
            return
        def remove_book(self, isbn):
            return
        books = []

    monkeypatch.setattr("api.lib", FakeLibrary())

    # POST ekleme
    response = client.post("/books", json={"isbn": "123456"})
    assert response.status_code == 200
    assert "Kitap başarıyla eklendi" in response.json()["message"]

    # DELETE silme
    response = client.delete("/books/123456")
    assert response.status_code == 200
    assert "Kitap silindi" in response.json()["message"]