# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMwO8FuMgAILh2xdcZB_2HiWvI8hbcG1
"""

class Book:
    def __init__(self, title, author, isbn):
        self.title = title
        self.author = author
        self.isbn = isbn

    def to_dict(self):
        """Kitap nesnesini sözlük formatına çevirir"""
        return {
            "title": self.title,
            "author": self.author,
            "isbn": self.isbn
        }

    def __str__(self):
        return f"{self.title} by {self.author} (ISBN: {self.isbn})"