# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AK_9dI5enKnlNCbFKDy_IY-vehMah_j
"""

import os
import pytest
from book import Book
from library import Library

TEST_JSON = "test_library.json"

@pytest.fixture
def library():
    # Test kütüphanesi oluştur
    lib = Library(TEST_JSON)
    lib.books = []
    lib.save_books()
    yield lib
    # Test dosyasını temizle
    if os.path.exists(TEST_JSON):
        os.remove(TEST_JSON)

def test_add_and_find_book(library):
    book = Book("Test Kitap", "Test Yazar", "123456")
    library.add_book(book)
    # ISBN ile bulma
    found = [b for b in library.books if b.isbn == "123456"]
    assert len(found) == 1
    assert found[0].title == "Test Kitap"

def test_remove_book(library):
    book = Book("Silinecek Kitap", "Yazar", "111111")
    library.add_book(book)
    library.remove_book("111111")
    found = [b for b in library.books if b.isbn == "111111"]
    assert len(found) == 0