# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AK_9dI5enKnlNCbFKDy_IY-vehMah_j
"""

import json
import httpx
from book import Book

class Library:
    def __init__(self, json_file='library.json'):
        self.json_file = json_file
        self.books = self.load_books()

    def load_books(self):
        try:
            with open(self.json_file, 'r') as f:
                data = json.load(f)
                return [Book(**book) for book in data]
        except (FileNotFoundError, json.JSONDecodeError):
            return []

    def save_books(self):
        with open(self.json_file, 'w') as f:
            json.dump([book.to_dict() for book in self.books], f, indent=4)

    def add_book_by_isbn(self, isbn):
        if any(b.isbn == isbn for b in self.books):
            print("Bu ISBN zaten mevcut!")
            return

        url = f"https://openlibrary.org/isbn/{isbn}.json"
        try:
            response = httpx.get(url, timeout=10)
            response.raise_for_status()
            data = response.json()
            title = data.get("title", "Bilinmeyen Başlık")
            authors_data = data.get("authors", [])
            authors = []
            for a in authors_data:
                author_url = f"https://openlibrary.org{a['key']}.json"
                author_resp = httpx.get(author_url, timeout=10)
                author_resp.raise_for_status()
                authors.append(author_resp.json().get("name", "Bilinmeyen Yazar"))
            author_str = ", ".join(authors) if authors else "Bilinmeyen Yazar"

            book = Book(title, author_str, isbn)
            self.books.append(book)
            self.save_books()
            print(f"{title} başarıyla eklendi.")
        except httpx.RequestError:
            print("API bağlantı hatası. Lütfen internet bağlantınızı kontrol edin.")
        except httpx.HTTPStatusError:
            print("Geçersiz ISBN veya kitap bulunamadı.")

    def remove_book(self, isbn):
        for book in self.books:
            if book.isbn == isbn:
                self.books.remove(book)
                self.save_books()
                print(f"{book.title} silindi.")
                return
        print("Kitap bulunamadı.")

    def list_books(self):
        if not self.books:
            print("Kütüphane boş.")
            return
        for book in self.books:
            print(book)

    def find_by_isbn(self, isbn):
        for book in self.books:
            if book.isbn == isbn:
                print(book)
                return
        print("Kitap bulunamadı.")