# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AK_9dI5enKnlNCbFKDy_IY-vehMah_j
"""

from library import Library

def main():
    lib = Library()
    while True:
        print("\n--- Kütüphane Menüsü ---")
        print("1. ISBN ile kitap ekle")
        print("2. Kitap sil")
        print("3. Kitapları listele")
        print("4. ISBN ile ara")
        print("5. Çıkış")
        choice = input("Seçiminiz: ")

        if choice == '1':
            isbn = input("Kitabın ISBN'i: ")
            lib.add_book_by_isbn(isbn)
        elif choice == '2':
            isbn = input("Silinecek kitabın ISBN'i: ")
            lib.remove_book(isbn)
        elif choice == '3':
            lib.list_books()
        elif choice == '4':
            isbn = input("Aranacak ISBN: ")
            lib.find_by_isbn(isbn)
        elif choice == '5':
            print("Çıkış yapılıyor...")
            break
        else:
            print("Geçersiz seçim!")

if __name__ == "__main__":
    main()