# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18AK_9dI5enKnlNCbFKDy_IY-vehMah_j
"""

import pytest
from library import Library

def test_add_book_by_isbn(monkeypatch):
    lib = Library("test_library.json")
    lib.books = []

    # Monkeypatch ile httpx.get simülasyonu
    class FakeResponse:
        def __init__(self, json_data):
            self._json = json_data

        def raise_for_status(self):
            pass

        def json(self):
            return self._json

    def fake_get(url, timeout=10):
        if "authors" in url:
            return FakeResponse({"name": "Test Yazar"})
        return FakeResponse({"title": "Test Kitap", "authors":[{"key":"/authors/OL1A"}]})

    monkeypatch.setattr("httpx.get", fake_get)

    lib.add_book_by_isbn("123456")
    assert len(lib.books) == 1
    assert lib.books[0].title == "Test Kitap"
    assert lib.books[0].author == "Test Yazar"